import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import { useEffect } from "react";
import {
  detainStudentFromExam,
  getDetainedStudents,
  getStudentAttendanceByMonth,
  markStudentAttendanceMultiple,
} from "@/utils/api/services";

export default function Home() {
  useEffect(() => {
    async function getData() {
      const res = await getDetainedStudents(2023, "CER4C3");
      console.log({ res });
    }
    async function detainStudent() {
      const res = await detainStudentFromExam(
        "2023",
        "CER4C3",
        "mst3",
        "DE19152"
      );
      console.log({ res });
    }
    async function markAttendance() {
      const res = await markStudentAttendanceMultiple(
        "CER4C3",
        "19_02_2023",
        ["DE19152", "DE19157"],
        "present"
      );
      console.log({ res });
    }
    async function getAttendanceByMonth() {
      const res = await getStudentAttendanceByMonth(
        "2023",
        "CER4C3",
        "DE19152",
        2
      );
      console.log({ res });
    }
    // getData();
    // detainStudent();
    // markAttendance();
    getAttendanceByMonth();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>IET Attendance</main>
    </>
  );
}
