import Head from "next/head";
import { useEffect, useState } from "react";
import { attendanceServices, studentServices } from "@/utils/api/services";
const { getAllStudentsByYear } = studentServices;
import {
  getToday12AMDatetime,
  getTotalDaysCountInCurrentMonth,
} from "@/utils/functions";
import styles from "../styles/main.module.scss";
import { Button, DatePicker, Pagination, Table } from "antd";
import { PlusOutlined } from "@ant-design/icons";
import MainLayout from "@/layouts/MainLayout/MainLayout";
const { RangePicker } = DatePicker;

// rowSelection object indicates the need for row selection
const rowSelection = {
  onChange: (selectedRowKeys: React.Key[], selectedRows: any[]) => {
    console.log(
      `selectedRowKeys: ${selectedRowKeys}`,
      "selectedRows: ",
      selectedRows
    );
  },
  getCheckboxProps: (record: any) => ({
    disabled: record.name === "Disabled User", // Column configuration not to be checked
    name: record.name,
  }),
};

export default function Home() {
  const [students, setStudents] = useState([]);
  const [attendance, setAttendance] = useState([]);
  const [detainedStudents, setDetainedStudents] = useState([]);
  const [currentDatePagination, setCurrentDatePagination] = useState(1);

  const columns = [
    {
      title: "Roll No.",
      dataIndex: "rollID",
      key: "rollID",
    },
    {
      title: "Enrollment No.",
      dataIndex: "uid",
      key: "rollID",
    },
    {
      title: "Name",
      dataIndex: "name",
      key: "name",
    },
  ];

  useEffect(() => {
    const fetchStudents = async () => {
      const { data } = await getAllStudentsByYear("2019");
      setStudents(data.data);
    };
    // const fetchAttendance = async () => {
    //   const { data } = await attendanceServices.getAttendanceBySubjectAndDate(getToday12AMDatetime());
    //   setAttendance(data.data);
    // }
    fetchStudents();
  }, []);

  return (
    <>
      <Head>
        <title>IET Attendance</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout className={styles.main}>
        <div className={styles.flexRow}>
          <h3>IET Attendance</h3>
          <div>
            <RangePicker />
            <Button icon={<PlusOutlined />} type="primary">
              New Attendance
            </Button>
          </div>
        </div>
        <div className={styles.tableContainer}>
          <Table
            rowSelection={{
              type: "checkbox",
              ...rowSelection,
            }}
            columns={columns}
            dataSource={students}
          />
        </div>
      </MainLayout>
    </>
  );
}
